apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-PLACEHOLDER_TAG_ENV-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-PLACEHOLDER_TAG_ENV
  template:
    metadata:
      labels:
        app: backend-PLACEHOLDER_TAG_ENV
    spec:
      containers:
        - name: backend-PLACEHOLDER_TAG_ENV
          image: deval2498/baserepo-PLACEHOLDER_TAG_DOCKER_BUILD:PLACEHOLDER_TAG_SHA  # Change to your image
          ports:
            - containerPort: PLACEHOLDER_TAG_PORT
          env:
            - name: PORT
              value: PLACEHOLDER_TAG_PORTSTRING
